---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{ download }}/{{ file }}"

- name: download {{ jmx_trans }}
  run_once: true
  get_url:
    url: "{{ jmx_trans }}"
    dest: "{{ download }}/jmxtrans-agent.jar"

- name: install {{ download }}/{{ file }}
  become: yes
  become_method: sudo
  yum:
    name: "{{ download }}/{{ file }}"
    state: present

- name: set JAVA_HOME=/usr/java/latest
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/java.sh"
    create: yes
    state: present
    regexp: '^export JAVA_HOME'
    line: 'export JAVA_HOME=/usr/java/latest'
