- hosts: all
  remote_user: vagrant
  serial: 100%
  roles:
  - java

- hosts: zookeeper
  remote_user: vagrant
  serial: 100%
  roles:
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  serial: 100%
  roles:
    - kafka

- hosts: cassandra
  remote_user: vagrant
  serial: 100%
  roles:
    - cassandra

- hosts: hadoop-master
  remote_user: vagrant
  serial: 100%
  roles:
    - hadoop

- hosts: hadoop-slave
  remote_user: vagrant
  serial: 100%
  roles:
    - hadoop

- hosts: hadoop-master
  remote_user: vagrant
  serial: 100%
  roles:
    - spark
#    - flink
